name: Build (Windows MinGW)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MSYS2 and MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-pkg-config

    - name: Configure CMake
      shell: msys2 {0}
      run: |
        cmake -S . -B build -G "MinGW Makefiles" \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      shell: msys2 {0}
      run: cmake --build build -- -j4
